### ISSUE TITLE
Bears-Project-4 to Bears-Project-9 repo invite

### ISSUE THREAD

**Issue by cvonwilczur** [chingu-voyages/voyage-issues#2]
Hey there! Can Bears-Team-4 members be reinvited to the Bears-Project-9 repo? We were added to Team 9 but when the invites went out, they were for our original project repos rather than the consolidated repo. This would be for myself and @spicybyte on Slack.

**Comment by cvonwilczur** [comment]
@the-vampiire Could we also get user tara-fenton added to our repo? Thanks!

**Comment by the-vampiire** [comment]
i set all team members as admins of the repo. you should be able to invite her directly. let me know if youre unable to invite her @cvonwilczur
